### ISSUE TITLE
Example in article about :checked pseudo-class is not working

### ISSUE THREAD

**Issue by Walkeryr** [codrops/css-reference-issues#19]
Article [link](http://tympanus.net/codrops/css_reference/checked/).

![fwyohlabhz](https://cloud.githubusercontent.com/assets/1271366/6201169/0eb6a8ba-b4ab-11e4-9f2a-97b9431c07a6.gif)

That's because in css code there is no equals sign in attribute selector:

``` css
input[type "checkbox"]:checked + label {
  text-decoration: line-through;
  color: grey;
}
```
