### ISSUE TITLE
CanIUse table height issue

### ISSUE THREAD

**Issue by ronaldtveen** [codrops/css-reference-issues#28]
I guess `.ct-cssref .ct-cssref-support iframe` is missing 10 pixels in height, which results in a small 10px vertical scrollbar and the clipping of the footer text, see attached image.

``` css
/* Can I use embed */
.ct-cssref .ct-cssref-support iframe {
    width: 100%;
    height: 370px; /* settings this to 380px fixes it for me on Chrome 42.0.2311.135 */
    margin: 30px 0;
}
```

![can-i-use-footer](https://cloud.githubusercontent.com/assets/7911547/7608502/64e0a9d0-f96a-11e4-9930-f64911045689.png)
