### ISSUE TITLE
Grid: swap columns and rows in comments

### ISSUE THREAD

**Issue by msarris** [codrops/css-reference-issues#74]
In the Grid guide there are a few comments like the following:

```css
.grid-container {
  grid-template-columns: 150px 150px 150px; /* three rows  */
  grid-template-rows: 150px 150px; /* two columns  */
}
```

https://tympanus.net/codrops/css_reference/grid/#section_grid-tracks-cells

Maybe I misunderstand, but shouldn't rows and columns be swapped in the comments?
