### ISSUE TITLE
Add definition for `not` and `only` keywords in @media reference

### ISSUE THREAD

**Issue by xavierfoucrier** [codrops/css-reference-issues#91]
Write a short definition for the `not` and `only` keywords that can be used in a media query, for example to explain how a media query can be reversed:

```less
// set the paragraph color only between 0-399 and 601-*
@media not screen and (min-width: 400px) and (max-width: 600px) {
  p {
    color: blue;
  }
}
```

Here is the link to the specified page:
https://tympanus.net/codrops/css_reference/media.

Thanks again for the work on this site, I am using it all days :wink:
